[package]
name = "homological_algebra"
version = "0.1"
lean_version = "leanprover-community/lean:3.6.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "e8ad2e385d1546535a3badea6dedaf7b85c116a9"}
topos = {git = "https://github.com/b-mehta/topos", rev = "9e6a0d5d0958342679f8728ea03117ef538fc3cb"}
